
CREATE TABLE IF NOT EXISTS users (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  pseudo VARCHAR(15) NOT NULL,
  email VARCHAR(50) NOT NULL,
  passwrd TEXT NOT NULL,
  token TEXT NOT NULL,
  profile TEXT NOT NULL,
  notification VARCHAR(1) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS password_reset(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  token TEXT NOT NULL,
  email TEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS images(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Path TEXT COLLATE utf8_unicode_ci NOT NULL,
  USER int(11) COLLATE utf8_unicode_ci NOT NULL,
  FOREIGN KEY (USER)
    REFERENCES users (ID)
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS likes(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  imageID int(11) COLLATE utf8_unicode_ci NOT NULL,
  USER int(11) COLLATE utf8_unicode_ci NOT NULL,
  FOREIGN KEY (USER)
    REFERENCES users (ID)
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS comment(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  USER int(11) COLLATE utf8_unicode_ci NOT NULL,
  COMMENT TEXT COLLATE utf8_unicode_ci NOT NULL,
  imageID int(11) COLLATE utf8_unicode_ci NOT NULL,
  comment_id TEXT COLLATE utf8_unicode_ci NOT NULL,
  FOREIGN KEY (USER)
    REFERENCES users (ID)
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `block`(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  blocker_id int(11) COLLATE utf8_unicode_ci NOT NULL,
  blocked_id int(11) COLLATE utf8_unicode_ci NOT NULL,
  FOREIGN KEY (blocker_id)
    REFERENCES users (ID)
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;